if (process.env.NODE_ENV !== 'production') {
  require('dotenv').config()
}
const express = require('express')
const cors = require('cors')
const ProductController = require('./controllers/productController')
const TransactionController = require('./controllers/transactionController')
const handleMainRequest = require('./controllers/midtransController')
const UserController = require('./controllers/userController')
const authentication = require('./middlewares/authentication')
const errorHandler = require('./middlewares/errorHandler')
const MemberController = require('./controllers/memberController')
const ReferralController = require('./controllers/referralController')
const DepositHistoryController = require('./controllers/DepositHistory')
const port = process.env.PORT || 3000
const app = express()

app.use(express.urlencoded({ extended: true }))
app.use(express.json())
app.use(cors())

app.post('/register', UserController.register)
app.post('/login', UserController.login)
app.get('/products', ProductController.getProducts)
app.post('/products', ProductController.createProduct)
app.delete('/produts/:id', ProductController.delProduct)

app.use(authentication)

app.get('/user', UserController.getDataUser)
app.patch('/user', UserController.topUpUser)
app.patch('/user/deposit', UserController.moveCashback)
app.patch('/user/referral', UserController.moveReferral)
app.patch('/user/reward', UserController.moveReward)
app.patch('/user/buy', UserController.buyBalance)
app.get('/transaction', TransactionController.getDataTransaction)
app.post('/transaction', TransactionController.createTransaction)
app.post('/member', MemberController.createMember)
app.get('/member', MemberController.getDataMember)
app.get('/member/chart', MemberController.getDataMemberChart)
app.get('/reward', MemberController.getRewardHistory)
app.delete('/member/:id', MemberController.delMember)
app.get('/member/except', MemberController.getDataMemberExcept)
app.get('/referral', ReferralController.getDataReferral)
app.get('/referral/all', ReferralController.getAllDataReferral)
app.get('/deposit', DepositHistoryController.getDeposit)
app.post('/order', handleMainRequest)
app.use(errorHandler)

app.listen(port, () => console.log('Listening on port', port))
